Repository openiddict/openiddict-core, pull requests merged in 2020-08, with the labels that each got.

#1046 Temporarily remove the nullable reference annotations from the 4 managers interfaces
  src/OpenIddict.Abstractions/Managers/IOpenIddictApplicationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictAuthorizationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictScopeManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictTokenManager.cs
Labels: bug, external

#1047 Improve the French translation
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.fr.xlf
Labels: enhancement, localization

#1052 Introduce OpenIddict.Server.Quartz
  Directory.Packages.props
  NuGet.config
  OpenIddict.sln
  samples/Mvc.Server/Mvc.Server.csproj
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.fr.xlf
  src/OpenIddict.Server.Quartz/OpenIddict.Server.Quartz.csproj
  src/OpenIddict.Server.Quartz/OpenIddictServerQuartzBuilder.cs
  src/OpenIddict.Server.Quartz/OpenIddictServerQuartzExtensions.cs
  src/OpenIddict.Server.Quartz/OpenIddictServerQuartzJob.cs
  src/OpenIddict.Server.Quartz/OpenIddictServerQuartzOptions.cs
  test/OpenIddict.Server.Quartz.Tests/OpenIddict.Server.Quartz.Tests.csproj
  test/OpenIddict.Server.Quartz.Tests/OpenIddictServerQuartzBuilderTests.cs
  test/OpenIddict.Server.Quartz.Tests/OpenIddictServerQuartzExtensionsTests.cs
  test/OpenIddict.Server.Quartz.Tests/OpenIddictServerQuartzJobTests.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement, important

#1054 Add spanish support and error messages
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.es.xlf
Labels: enhancement, localization

#1056 Bump the .NET SDK/runtime and the ASP.NET Core/.NET Platform Extensions packages
  Directory.Packages.props
  global.json
Labels: enhancement

#1057 Update XlfLanguages to generate OpenIddictResources.it.xlf
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.it.xlf
Labels: enhancement, localization

#1058 Update XlfLanguages to generate OpenIddictResources.ar.xlf
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.ar.xlf
Labels: enhancement, localization

#1060 Add Chinese translations
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hans.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hant.xlf
Labels: enhancement, localization

#1062 Update XlfLanguages to generate OpenIddictResources.gu.xlf and OpenIddictResources.hi.xlf
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.gu.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.hi.xlf
Labels: enhancement, localization

#1063 Update XlfLanguages to generate OpenIddictResources.tr.xlf
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf
Labels: enhancement, localization

#1064 Add Turkish Translations to Messages
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf
Labels: enhancement, localization

#1065 Added Hindi translations
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.hi.xlf
Labels: enhancement, localization

#1066 Update XlfLanguages to generate OpenIddictResources.ru.xlf and OpenIddictResources.uk.xlf
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.ru.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.uk.xlf
Labels: enhancement, localization

#1067 Update XlfLanguages to generate OpenIddictResources.de.xlf
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.de.xlf
Labels: enhancement, localization

#1059 Add Arabic translations
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.ar.xlf
Labels: enhancement, localization

#1061 Add Italian translations
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.it.xlf
Labels: enhancement, localization

#1072 Add German translations
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.de.xlf
Labels: enhancement, localization

#1074 Update the ConvertReferenceUserCode handler to generate a new user code when a collision is detected
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
Labels: enhancement

#1078 Use T? on unconstrained type parameters
  Directory.Build.props
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictScopeManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkApplication.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkAuthorization.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkScope.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkToken.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkApplicationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkAuthorizationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkScopeStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkTokenStore.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreApplication.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreAuthorization.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreScope.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreToken.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreScopeStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Validation/OpenIddictValidationBuilder.cs
Labels: enhancement, important
