Repository openiddict/openiddict-core, pull requests merged in 2020-10, with the labels that each got.

#1107 Bump Quartz.NET and leverage its new Microsoft.Extensions.Options support
  Directory.Packages.props
  NuGet.config
  src/OpenIddict.Quartz/OpenIddict.Quartz.csproj
  src/OpenIddict.Quartz/OpenIddictQuartzConfiguration.cs
  src/OpenIddict.Quartz/OpenIddictQuartzExtensions.cs
  test/OpenIddict.Quartz.Tests/OpenIddictQuartzConfigurationTests.cs
  test/OpenIddict.Quartz.Tests/OpenIddictQuartzExtensionsTests.cs
Labels: enhancement

#1108 Add Dutch (nl) resource file
  Directory.Build.props
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.nl.xlf
Labels: localization

#1110 Rename Enable*EndpointCaching to Enable*RequestCaching
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreBuilder.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreExtensions.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlerFilters.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreOptions.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinBuilder.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinExtensions.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlerFilters.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Authentication.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinOptions.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Authentication.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Session.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Authentication.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Session.cs
Labels: enhancement

#1112 Ensure cached JsonElement instances are always cloned
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkApplicationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkAuthorizationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkScopeStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkTokenStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreScopeStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbApplicationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbAuthorizationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbScopeStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbTokenStore.cs
Labels: bug, important

#1116 Enable nullable reference types support in the unit/integration tests…
  test/OpenIddict.Abstractions.Tests/OpenIddict.Abstractions.Tests.csproj
  test/OpenIddict.Abstractions.Tests/OpenIddictBuilderTests.cs
  test/OpenIddict.Abstractions.Tests/OpenIddictExtensionsTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictConverterTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictMessageTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictParameterTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictRequestTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictResponseTests.cs
  test/OpenIddict.Core.Tests/OpenIddict.Core.Tests.csproj
  test/OpenIddict.Core.Tests/OpenIddictCoreBuilderTests.cs
  test/OpenIddict.Core.Tests/OpenIddictCoreExtensionsTests.cs
  test/OpenIddict.EntityFramework.Tests/OpenIddict.EntityFramework.Tests.csproj
  test/OpenIddict.EntityFramework.Tests/OpenIddictEntityFrameworkBuilderTests.cs
  test/OpenIddict.EntityFramework.Tests/OpenIddictEntityFrameworkExtensionsTests.cs
  test/OpenIddict.EntityFrameworkCore.Tests/OpenIddict.EntityFrameworkCore.Tests.csproj
  test/OpenIddict.EntityFrameworkCore.Tests/OpenIddictEntityFrameworkCoreBuilderTests.cs
  test/OpenIddict.EntityFrameworkCore.Tests/OpenIddictEntityFrameworkCoreExtensionsTests.cs
  test/OpenIddict.MongoDb.Tests/OpenIddict.MongoDb.Tests.csproj
  test/OpenIddict.MongoDb.Tests/OpenIddictMongoDbBuilderTests.cs
  test/OpenIddict.MongoDb.Tests/OpenIddictMongoDbExtensionsTests.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddict.Server.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTestServer.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Exchange.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Introspection.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Revocation.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestClient.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Revocation.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Session.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Userinfo.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddict.Server.Owin.IntegrationTests.csproj
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Exchange.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Introspection.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Revocation.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
  test/OpenIddict.Server.Tests/OpenIddict.Server.Tests.csproj
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement

#1119 Replace DateTimeOffset by DateTime in the EF Core/EF 6 models
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkAuthorization.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkToken.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkAuthorizationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkTokenStore.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreAuthorization.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreToken.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbAuthorization.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbToken.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbAuthorizationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbTokenStore.cs
Labels: important

#1120 Use DateTime instances in the EF Core/EF 6 queries
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkAuthorizationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkTokenStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
Labels: bug

#1121 Update the MongoDB token store to use UtcDateTime
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbTokenStore.cs
Labels: enhancement

#1123 Update the MongoDB stores to use ImmutableList instead of ImmutableArray
  samples/Mvc.Server/Worker.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbApplication.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbAuthorization.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbScope.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbApplicationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbAuthorizationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbScopeStore.cs
Labels: bug, important

#1126 Use ECCurve.Oid.Value when comparing EC curves
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
Labels: bug

#1129 Add instructions for referencing the MyGet feed to README
  README.md
Labels: enhancement

#1100 Use the new SecurityTokenDescriptor.TokenType property
  Directory.Packages.props
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Authentication.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
Labels: enhancement

#1130 Stop using NuGet's Central Package Version Management feature
  Directory.Build.props
  Directory.Build.targets
  Directory.Packages.props
  OpenIddict.sln
  Packages.props
Labels: important

#1131 Bump the .NET SDK, the .NET/ASP.NET packages and the third-party dependencies
  Packages.props
  eng/CodeAnalysis.ruleset
  global.json
  src/OpenIddict.EntityFrameworkCore/OpenIddictEntityFrameworkCoreHelpers.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreScopeStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
Labels: enhancement

#1135 Use C# 9 pattern matching
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  src/OpenIddict.Server/OpenIddictServerDispatcher.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Validation/OpenIddictValidationDispatcher.cs
Labels: enhancement

#1136 Optimization: handle JsonValueKind.Null values earlier in OpenIddictParameter.WriteTo()
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
Labels: enhancement

#1137 Bump Quartz.NET to 3.2.1
  Packages.props
  test/OpenIddict.Quartz.Tests/OpenIddictQuartzConfigurationTests.cs
Labels: enhancement

#1142 Introduce response type permissions, remove hybrid clients support and bring back none flow support
  samples/Mvc.Server/Worker.cs
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.ar.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.de.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.es.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.fr.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.gu.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.hi.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.it.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.nl.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hans.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hant.xlf
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerExtensions.cs
  src/OpenIddict.Server/OpenIddictServerHandlerFilters.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement

#1143 Add a new option allowing to make PKCE mandatory
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement

#1144 Update the samples to enable SSL/TLS
  samples/Mvc.Client/Controllers/HomeController.cs
  samples/Mvc.Client/Properties/launchSettings.json
  samples/Mvc.Client/Startup.cs
  samples/Mvc.Server/Properties/launchSettings.json
  samples/Mvc.Server/Worker.cs
Labels: bug, important

#1147 Revamp refresh tokens
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictTokenDescriptor.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictAuthorizationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictTokenManager.cs
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Stores/IOpenIddictTokenStore.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkToken.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkTokenStore.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreToken.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbToken.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbTokenStore.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreBuilder.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinBuilder.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerExtensions.cs
  src/OpenIddict.Server/OpenIddictServerHandlerFilters.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement, important

#1149 Stop adding a jti claim by default
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
Labels: enhancement

#1150 Bump Quartz.NET to 3.2.2
  Packages.props
Labels: enhancement

#1155 Update the ValidateScopes handlers to lazily resolve IOpenIddictScopeManager
  src/OpenIddict.Server/OpenIddictServerHandlerDescriptor.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlerDescriptor.cs
Labels: bug
