Repository openiddict/openiddict-core, pull requests merged in 2020-07, with the labels that each got.

#997 Support the long application/at+jwt and application/jwt forms
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
Labels: enhancement

#998 Update ValidateIdentityModelToken and ValidateDataProtectionToken to immediately return an error when the token can be read but is invalid
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
Labels: enhancement

#999 Cross-compile more projects for .NET Framework 4.6.1 to reduce the dependencies graph
  Directory.Build.props
  src/OpenIddict.Abstractions/OpenIddict.Abstractions.csproj
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/OpenIddict.Core.csproj
  src/OpenIddict.EntityFramework.Models/OpenIddict.EntityFramework.Models.csproj
  src/OpenIddict.EntityFramework/OpenIddict.EntityFramework.csproj
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddict.EntityFrameworkCore.Models.csproj
  src/OpenIddict.EntityFrameworkCore/OpenIddict.EntityFrameworkCore.csproj
  src/OpenIddict.MongoDb.Models/OpenIddict.MongoDb.Models.csproj
  src/OpenIddict.MongoDb/OpenIddict.MongoDb.csproj
  src/OpenIddict.Server.AspNetCore/OpenIddict.Server.AspNetCore.csproj
  src/OpenIddict.Server.DataProtection/OpenIddict.Server.DataProtection.csproj
  src/OpenIddict.Server.Owin/OpenIddict.Server.Owin.csproj
  src/OpenIddict.Server/OpenIddict.Server.csproj
  src/OpenIddict.Validation.AspNetCore/OpenIddict.Validation.AspNetCore.csproj
  src/OpenIddict.Validation.DataProtection/OpenIddict.Validation.DataProtection.csproj
  src/OpenIddict.Validation.Owin/OpenIddict.Validation.Owin.csproj
  src/OpenIddict.Validation.ServerIntegration/OpenIddict.Validation.ServerIntegration.csproj
  src/OpenIddict.Validation.SystemNetHttp/OpenIddict.Validation.SystemNetHttp.csproj
  src/OpenIddict.Validation/OpenIddict.Validation.csproj
  src/OpenIddict/OpenIddict.csproj
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddict.Server.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.Tests/OpenIddict.Server.Tests.csproj
Labels: enhancement

#1001 Cross-compile more projects for .NET Core 2.1/3.1 to avoid the Portable.BouncyCastle reference in ASP.NET Core 2.1 applications
  src/OpenIddict.Core/OpenIddict.Core.csproj
  src/OpenIddict.EntityFrameworkCore/OpenIddict.EntityFrameworkCore.csproj
  src/OpenIddict.MongoDb/OpenIddict.MongoDb.csproj
  src/OpenIddict.Server.DataProtection/OpenIddict.Server.DataProtection.csproj
  src/OpenIddict/OpenIddict.csproj
Labels: enhancement

#1002 Introduce new filters to avoid instantiating scoped handlers when unnecessary
  src/OpenIddict.Server/OpenIddictServerDispatcher.cs
  src/OpenIddict.Server/OpenIddictServerExtensions.cs
  src/OpenIddict.Server/OpenIddictServerHandlerFilters.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Userinfo.cs
  src/OpenIddict.Validation/OpenIddictValidationDispatcher.cs
Labels: enhancement

#1003 Revamp the access token extraction logic used in the validation stack
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationService.cs
Labels: enhancement

#1004 Switch to GitHub Actions for CI/CD
  .github/workflows/build.yml
  .travis.yml
  Directory.Build.props
  README.md
  appveyor.yml
Labels: enhancement

#1006 Move the OfficialBuildId computation logic to build.yml
  .github/workflows/build.yml
  Directory.Build.props
  OpenIddict.sln
Labels: enhancement

#1007 Send integration test logs to xunit output
  .gitignore
  Directory.Packages.props
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
Labels: enhancement

#1008 Update the logout endpoint logic to not trigger a sign-out response by default and reword some of the exception messages
  src/OpenIddict.Server/OpenIddictServerEvents.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerEvents.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerEvents.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Session.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Session.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
Labels: enhancement, important

#1009 Configure the OWIN server integration test server to use ITestOutputHelper
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
Labels: enhancement

#1010 Change the action level of the CA1725 rule and update affected methods
  eng/CodeAnalysis.ruleset
  samples/Mvc.Server/Helpers/FormValueRequiredAttribute.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictConverter.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  src/OpenIddict.EntityFrameworkCore/OpenIddictEntityFrameworkCoreCustomizer.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictConverterTests.cs
Labels: enhancement

#1011 Update the XML documentation
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionOptions.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionBuilder.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionOptions.cs
  src/OpenIddict.Validation.SystemNetHttp/OpenIddictValidationSystemNetHttpHelpers.cs
Labels: enhancement

#1012 Move the feature constants from Directory.Build.props to Directory.Build.targets to be able to use TargetFrameworkIdentifier-based conditions
  Directory.Build.props
  Directory.Build.targets
  Directory.Packages.props
  src/OpenIddict.Abstractions/OpenIddict.Abstractions.csproj
  src/OpenIddict.Core/OpenIddict.Core.csproj
  src/OpenIddict.Server/OpenIddict.Server.csproj
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddict.Server.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddict.Server.Owin.IntegrationTests.csproj
  test/OpenIddict.Server.Tests/OpenIddict.Server.Tests.csproj
Labels: enhancement

#1013 Bump all the referenced packages to their latest version, including .NET Extensions and ASP.NET Core
  Directory.Packages.props
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbApplicationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbAuthorizationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbScopeStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbTokenStore.cs
Labels: enhancement

#1014 Remove the .NET Framework 4.7.2 TFM from OpenIddict.Owin, OpenIddict.Server.Owin and OpenIddict.Validation.Owin
  src/OpenIddict.Owin/OpenIddict.Owin.csproj
  src/OpenIddict.Server.Owin/OpenIddict.Server.Owin.csproj
  src/OpenIddict.Validation.Owin/OpenIddict.Validation.Owin.csproj
Labels: enhancement

#1015 Add placeholders to the OpenIddict, OpenIddict.AspNetCore and OpenIddict.Owin metapackages
  src/OpenIddict.AspNetCore/OpenIddict.AspNetCore.csproj
  src/OpenIddict.AspNetCore/_._
  src/OpenIddict.Owin/OpenIddict.Owin.csproj
  src/OpenIddict.Owin/_._
  src/OpenIddict/OpenIddict.csproj
  src/OpenIddict/_._
Labels: bug

#1016 Remove /p:DotNetPublishUsingPipelines=true to ensure SourceLink works correctly
  .github/workflows/build.yml
  Directory.Build.props
Labels: bug, important

#1017 Add OpenIddictParameter.Count
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictParameterTests.cs
Labels: enhancement

#1018 Update GetNamedParameters()/GetUnnamedParameters() to use cached empty instances
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
Labels: enhancement

#1019 Update the TypeValidator custom delegate to avoid throwing when the JWT token has no "typ" header but contains a "token_usage" claim
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
Labels: enhancement

#1020 Update IntrospectToken to immediately return an error when introspection fails and match ValidateIdentityModelToken
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
Labels: enhancement

#1021 Port the workflow changes from aspnet-contrib
  .github/workflows/build.yml
Labels: bug

#1023 Rename OpenIddictServerOptions.UseSlidingExpiration to DisableSlidingRefreshTokenExpiration and fix the XML documentation
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerExtensions.cs
  src/OpenIddict.Server/OpenIddictServerHandlerFilters.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement

#1024 Revamp the encryption/signing credentials registration mechanism
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation.ServerIntegration/OpenIddictValidationServerIntegrationConfiguration.cs
  src/OpenIddict.Validation/OpenIddictValidationBuilder.cs
  src/OpenIddict.Validation/OpenIddictValidationConfiguration.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement

#1027 Update OpenIddictValidationHandlers.Introspection.PopulateClaims to honor NameClaimType/RoleClaimType
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Introspection.cs
Labels: bug

#1028 Bump the .NET SDK/runtime and the ASP.NET Core/.NET Platform Extensions packages
  Directory.Build.targets
  Directory.Packages.props
  global.json
  src/OpenIddict.Abstractions/OpenIddict.Abstractions.csproj
  src/OpenIddict.Core/OpenIddict.Core.csproj
  src/OpenIddict.Server.AspNetCore/OpenIddict.Server.AspNetCore.csproj
  src/OpenIddict.Server.DataProtection/OpenIddict.Server.DataProtection.csproj
  src/OpenIddict.Server/OpenIddict.Server.csproj
  src/OpenIddict.Validation.AspNetCore/OpenIddict.Validation.AspNetCore.csproj
  src/OpenIddict.Validation.DataProtection/OpenIddict.Validation.DataProtection.csproj
Labels: enhancement

#1025 Implement localized descriptions/display names support
  samples/Mvc.Server/Controllers/AuthorizationController.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictApplicationDescriptor.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictAuthorizationDescriptor.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictScopeDescriptor.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictApplicationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictScopeManager.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  src/OpenIddict.Abstractions/Stores/IOpenIddictApplicationStore.cs
  src/OpenIddict.Abstractions/Stores/IOpenIddictScopeStore.cs
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictScopeManager.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkApplication.cs
  src/OpenIddict.EntityFramework.Models/OpenIddictEntityFrameworkScope.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkApplicationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkScopeStore.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreApplication.cs
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreScope.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreScopeStore.cs
  src/OpenIddict.MongoDb.Models/OpenIddict.MongoDb.Models.csproj
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbApplication.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbAuthorization.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbScope.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbApplicationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbAuthorizationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbScopeStore.cs
Labels: enhancement, important

#1030 Ensure the header name is always returned with the ID3081 error message
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
Labels: bug

#1031 Move all the assertions and log messages to OpenIddictResources
  src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.Core/OpenIddictCoreExtensions.cs
  src/OpenIddict.EntityFramework/OpenIddictEntityFrameworkBuilder.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Authentication.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerDispatcher.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Userinfo.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationDispatcher.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  test/OpenIddict.Core.Tests/OpenIddictCoreExtensionsTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
Labels: enhancement

#1032 Fix RedeemTokenEntry to use SR.ID3019 instead of a hardcoded string
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
Labels: bug, localization

#1034 Rename the FunctionalTests namespace suffix to IntegrationTests
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTestServer.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Authentication.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Exchange.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Introspection.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Revocation.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Session.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestClient.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestServer.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Revocation.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Session.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Userinfo.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTestServer.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Authentication.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Exchange.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Introspection.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Revocation.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Session.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
Labels: enhancement

#1038 Update the XML documentation to use <list type="bullet"> where appropriate
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
Labels: enhancement

#1039 Fix the x5c resolution logic used in the ExtractSigningKeys handler
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Discovery.cs
Labels: bug

#1040 Automatically disable the incompatible options when enabling the degraded mode
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: bug

#1041 Don't revoke the authorization when detecting an authorization code/refresh token replay
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
Labels: enhancement

#1043 Translate all the error messages into French and remove the duplicate .resx entries
  Directory.Build.props
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Abstractions/OpenIddict.Abstractions.csproj
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.fr.xlf
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Revocation.cs
Labels: enhancement, localization

#1044 Update the Set*EndpointUris methods to block relative paths starting with ~
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement

#1045 Disable the NU5118 warning
  Directory.Build.props
Labels: bug
