Repository openiddict/openiddict-core, pull requests merged in 2020-11, with the labels that each got.

#1152 Add key size validation for AddEncryptionKey
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement

#1157 Update OpenIddictMessage to ignore parameters with empty names
  src/OpenIddict.Abstractions/Primitives/OpenIddictMessage.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictRequest.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictResponse.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionFormatter.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Introspection.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictMessageTests.cs
Labels: bug, enhancement

#1084 Add back the nullable reference annotations in the 4 managers interfaces
  src/OpenIddict.Abstractions/Managers/IOpenIddictApplicationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictAuthorizationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictScopeManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictTokenManager.cs
Labels: bug, external

#1158 Introduce a new Import method in the handler descriptors
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerHandlerDescriptor.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlerDescriptor.cs
Labels: enhancement

#1160 Avoid mutating the issuer set in the options when computing the absolute OIDC metadata address
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.ar.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.de.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.es.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.fr.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.gu.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.hi.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.it.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.nl.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hans.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hant.xlf
  src/OpenIddict.Validation/OpenIddictValidationConfiguration.cs
Labels: bug

#1161 Fix ValidateResponseTypePermissions to use the correct log message identifier
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
Labels: bug

#1162 Ensure endpoint addresses are unique across endpoints
  .github/workflows/build.yml
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
Labels: enhancement

#1079 Add .NET 5.0 TFMs and bump the .NET SDK to 5.0.100
  Directory.Build.props
  Directory.Build.targets
  Packages.props
  global.json
  samples/Mvc.Client/Controllers/AuthenticationController.cs
  samples/Mvc.Client/Mvc.Client.csproj
  samples/Mvc.Client/Startup.cs
  samples/Mvc.Client/Views/Shared/Home.cshtml
  samples/Mvc.Server/Mvc.Server.csproj
  src/OpenIddict.Abstractions/OpenIddict.Abstractions.csproj
  src/OpenIddict.AspNetCore/OpenIddict.AspNetCore.csproj
  src/OpenIddict.Core/OpenIddict.Core.csproj
  src/OpenIddict.EntityFramework.Models/OpenIddict.EntityFramework.Models.csproj
  src/OpenIddict.EntityFramework/OpenIddict.EntityFramework.csproj
  src/OpenIddict.EntityFrameworkCore.Models/OpenIddict.EntityFrameworkCore.Models.csproj
  src/OpenIddict.EntityFrameworkCore/OpenIddict.EntityFrameworkCore.csproj
  src/OpenIddict.MongoDb.Models/OpenIddict.MongoDb.Models.csproj
  src/OpenIddict.MongoDb/OpenIddict.MongoDb.csproj
  src/OpenIddict.Quartz/OpenIddict.Quartz.csproj
  src/OpenIddict.Server.AspNetCore/OpenIddict.Server.AspNetCore.csproj
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.DataProtection/OpenIddict.Server.DataProtection.csproj
  src/OpenIddict.Server.Owin/OpenIddict.Server.Owin.csproj
  src/OpenIddict.Server/OpenIddict.Server.csproj
  src/OpenIddict.Validation.AspNetCore/OpenIddict.Validation.AspNetCore.csproj
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandler.cs
  src/OpenIddict.Validation.DataProtection/OpenIddict.Validation.DataProtection.csproj
  src/OpenIddict.Validation.Owin/OpenIddict.Validation.Owin.csproj
  src/OpenIddict.Validation.ServerIntegration/OpenIddict.Validation.ServerIntegration.csproj
  src/OpenIddict.Validation.SystemNetHttp/OpenIddict.Validation.SystemNetHttp.csproj
  src/OpenIddict.Validation/OpenIddict.Validation.csproj
  src/OpenIddict/OpenIddict.csproj
  test/OpenIddict.Abstractions.Tests/OpenIddict.Abstractions.Tests.csproj
  test/OpenIddict.Core.Tests/OpenIddict.Core.Tests.csproj
  test/OpenIddict.EntityFramework.Tests/OpenIddict.EntityFramework.Tests.csproj
  test/OpenIddict.EntityFrameworkCore.Tests/OpenIddict.EntityFrameworkCore.Tests.csproj
  test/OpenIddict.MongoDb.Tests/OpenIddict.MongoDb.Tests.csproj
  test/OpenIddict.Quartz.Tests/OpenIddict.Quartz.Tests.csproj
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddict.Server.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestClient.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddict.Server.Owin.IntegrationTests.csproj
  test/OpenIddict.Server.Tests/OpenIddict.Server.Tests.csproj
Labels: enhancement

#1163 Bump the .NET Core 3.x runtime/packages to 3.1.10
  Packages.props
  global.json
Labels: enhancement

#1165 Remove localized error descriptions support
  Directory.Build.props
  Packages.props
  samples/Mvc.Server/Controllers/AuthorizationController.cs
  src/OpenIddict.Abstractions/Resources/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.ar.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.de.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.es.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.fr.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.gu.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.hi.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.it.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.nl.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hans.xlf
  src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.zh-Hant.xlf
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictScopeManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.Core/OpenIddict.Core.csproj
  src/OpenIddict.Core/OpenIddictCoreExtensions.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinConstants.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Authentication.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddict.Server.csproj
  src/OpenIddict.Server/OpenIddictServerEvents.cs
  src/OpenIddict.Server/OpenIddictServerExtensions.cs
  src/OpenIddict.Server/OpenIddictServerFactory.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Userinfo.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerTransaction.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinConstants.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddict.Validation.csproj
  src/OpenIddict.Validation/OpenIddictValidationEvents.cs
  src/OpenIddict.Validation/OpenIddictValidationExtensions.cs
  src/OpenIddict.Validation/OpenIddictValidationFactory.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Discovery.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Introspection.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationTransaction.cs
  test/OpenIddict.Core.Tests/OpenIddictCoreBuilderTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: bug, important

#1048 894: Port the 2.x tests for OpenIddictServerExtensions for 3.x.
  test/OpenIddict.Server.Tests/OpenIddictServerExtensionsTests.cs
Labels: enhancement

#1167 Move OpenIddictResources.resx
  src/OpenIddict.Abstractions/OpenIddict.Abstractions.csproj
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreOptions.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinOptions.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
Labels: enhancement

#1168 React to nullable annotations changes in .NET 5.0 and update OpenIddictParameter.ToString() to use the invariant culture
  shared/OpenIddict.Extensions/Helpers/OpenIddictHelpers.cs
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkApplicationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkAuthorizationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkScopeStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreScopeStore.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionFormatter.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandler.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Userinfo.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandler.cs
  src/OpenIddict.Validation.DataProtection/OpenIddictValidationDataProtectionFormatter.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandler.cs
  src/OpenIddict.Validation.SystemNetHttp/OpenIddictValidationSystemNetHttpHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationBuilder.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Introspection.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationService.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictMessageTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictParameterTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestClient.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
Labels: enhancement

#1170 Introduce new APIs in the core managers to allow retrieving and adding additional properties
  src/OpenIddict.Abstractions/Descriptors/OpenIddictApplicationDescriptor.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictAuthorizationDescriptor.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictScopeDescriptor.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictTokenDescriptor.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictApplicationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictAuthorizationManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictScopeManager.cs
  src/OpenIddict.Abstractions/Managers/IOpenIddictTokenManager.cs
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictScopeManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
Labels: enhancement

#1171 Bump Arcade to 5.0.0-beta.20510.1
  eng/Version.Details.xml
  eng/common/cross/arm64/tizen-build-rootfs.sh
  eng/common/cross/arm64/tizen-fetch.sh
  eng/common/dotnet-install-scripts/dotnet-install.sh
  eng/common/internal/Directory.Build.props
  eng/common/native/find-native-compiler.sh
  eng/common/performance/performance-setup.sh
  eng/common/post-build/publish-using-darc.ps1
  eng/common/post-build/sourcelink-validation.ps1
  eng/common/post-build/symbols-validation.ps1
  eng/common/sdk-task.ps1
  eng/common/templates/job/job.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/jobs/source-build.yml
  eng/common/templates/post-build/channels/generic-internal-channel.yml
  eng/common/templates/post-build/channels/generic-public-channel.yml
  eng/common/templates/post-build/post-build.yml
  eng/common/templates/steps/perf-send-to-helix.yml
  eng/common/templates/steps/publish-logs.yml
  eng/common/templates/steps/send-to-helix.yml
  eng/common/templates/steps/source-build.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  global.json
Labels: enhancement

#1172 Update SetApplicationIdAsync()/SetAuthorizationIdAsync() to be compatible with QueryTrackingBehavior.NoTracking
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
Labels: bug

#1174 Block device requests sent by clients that were not granted the device code grant permission and add integration tests for the device and verification endpoints
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Device.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement

#1176 Add integration tests to ensure device/user codes are returned as part of sign-in operations triggered from the device endpoint
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement

#1177 Update ValidateIdentityModelToken to support additional exceptions
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
Labels: enhancement

#1178 Remove the parameter-less HasAudience()/HasPresenter()/HasResource()/HasScope() extensions
  src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs
Labels: enhancement

#1179 Bump third-party dependencies
  Packages.props
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationConfiguration.cs
Labels: dependencies

#1180 Improve the EC curves comparison logic
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
Labels: enhancement
