Repository openiddict/openiddict-core, pull requests merged in 2020-01, with the labels that each got.

#880 Port the introspection endpoint tests and enable basic authentication support
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Introspection.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Revocation.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Introspection.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Revocation.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Introspection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Introspection.cs
Labels: enhancement

#881 Port the revocation endpoint tests and disable GET support
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Revocation.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Revocation.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Revocation.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Revocation.cs
Labels: enhancement

#882 Port the userinfo integration tests and re-enable POST support
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Userinfo.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Userinfo.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Userinfo.cs
Labels: enhancement

#883 Port the end session endpoint integration tests
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.Session.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Session.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.Session.cs
Labels: enhancement

#884 Update the EF Core entity configurations to generate primary keys on add
  src/OpenIddict.EntityFrameworkCore/Configurations/OpenIddictApplicationConfiguration.cs
  src/OpenIddict.EntityFrameworkCore/Configurations/OpenIddictAuthorizationConfiguration.cs
  src/OpenIddict.EntityFrameworkCore/Configurations/OpenIddictScopeConfiguration.cs
  src/OpenIddict.EntityFrameworkCore/Configurations/OpenIddictTokenConfiguration.cs
Labels: bug, external

#885 Port the sign-in integration tests
  src/OpenIddict.Server/OpenIddictServerEvents.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerProvider.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement

#886 Port the discovery endpoints integration tests
  src/OpenIddict.Server.Owin/OpenIddictServerOwinMiddlewareFactory.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinMiddlewareFactory.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
Labels: enhancement

#888 Port the sign-out integration tests and add validation to prevent sign-out from being triggered from unsupported endpoints
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement

#889 Port the challenge integration tests
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
Labels: enhancement

#890 Update the OpenIddict server ASP.NET Core/OWIN integration tests to run on .NET Framework 4.6.1
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddict.Server.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddict.Server.IntegrationTests.csproj
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddict.Server.Owin.IntegrationTests.csproj
Labels: enhancement

#893 Update the server sample to use the authorization manager
  samples/Mvc.Server/Controllers/AuthorizationController.cs
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs
Labels: enhancement

#895 Enforce JWT access token encryption by default
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation.ServerIntegration/OpenIddictValidationServerIntegrationConfiguration.cs
Labels: enhancement, important

#896 Relax the relative URLs constraints and fix the Uri construction logic to correctly compute absolute URLs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationConfiguration.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Discovery.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: bug, enhancement

#897 Remove AddDevelopmentEncryptionCertificate()/AddEphemeralEncryptionKey() from OpenIddictValidationBuilder
  src/OpenIddict.Validation/OpenIddictValidationBuilder.cs
Labels: bug

#898 Add integration tests for the PKCE enforcement feature
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Authentication.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
Labels: enhancement

#902 Implement complete WWW-Authenticate response header support
  samples/Mvc.Client/Controllers/HomeController.cs
  samples/Mvc.Client/Startup.cs
  samples/Mvc.Server/Controllers/AuthorizationController.cs
  samples/Mvc.Server/Controllers/ResourceController.cs
  samples/Mvc.Server/Startup.cs
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictResponse.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreConfiguration.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreConstants.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Device.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Discovery.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Exchange.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Introspection.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Revocation.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Userinfo.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinConstants.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandler.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Authentication.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Device.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Discovery.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Exchange.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Introspection.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Revocation.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Userinfo.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Introspection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Revocation.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreConstants.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandler.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinConstants.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandler.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHelpers.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictResponseTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Introspection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Revocation.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement

#903 Adds a check for token requests containing a code_verifier parameter.
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Exchange.cs
Labels: enhancement

#904 Update OpenIddict.Validation.SystemNetHttp to use ReadAsStringAsync() and rework the samples
  samples/Mvc.Client/Program.cs
  samples/Mvc.Server/Program.cs
  samples/Mvc.Server/Startup.cs
  samples/Mvc.Server/Worker.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Validation.SystemNetHttp/OpenIddictValidationSystemNetHttpHandlers.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestClient.cs
Labels: enhancement
