Repository openiddict/openiddict-core, pull requests merged in 2022-07, with the labels that each got.

#1481 Make the "rfp" validation logic mandatory and move common helpers to OpenIddictHelpers
  sandbox/OpenIddict.Sandbox.AspNet.Client/OpenIddict.Sandbox.AspNet.Client.csproj
  sandbox/OpenIddict.Sandbox.AspNet.Server/OpenIddict.Sandbox.AspNet.Server.csproj
  shared/OpenIddict.Extensions/Helpers/OpenIddictHelpers.cs
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.AspNetCore/OpenIddict.Client.AspNetCore.csproj
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandler.cs
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandlers.cs
  src/OpenIddict.Client.Owin/OpenIddict.Client.Owin.csproj
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandler.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandlers.cs
  src/OpenIddict.Client/OpenIddict.Client.csproj
  src/OpenIddict.Client/OpenIddictClientService.cs
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Server/OpenIddict.Server.csproj
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
Labels: enhancement

#1483 Use static usings for the OpenIddict exceptions
  src/OpenIddict.Client/OpenIddictClientService.cs
  src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictScopeManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkApplicationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkAuthorizationStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkScopeStore.cs
  src/OpenIddict.EntityFramework/Stores/OpenIddictEntityFrameworkTokenStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreScopeStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbApplicationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbAuthorizationStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbScopeStore.cs
  src/OpenIddict.MongoDb/Stores/OpenIddictMongoDbTokenStore.cs
  src/OpenIddict.Validation/OpenIddictValidationService.cs
Labels: enhancement

#1484 Update OpenIddictHelpers.ParseQuery() to return parameters with empty values
  shared/OpenIddict.Extensions/Helpers/OpenIddictHelpers.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandlers.cs
Labels: bug

#1488 Fix logging statement
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
Labels: bug

#1490 Add integration tests projects for the client and validation stacks and use a high order for the AttachCustom*Parameters handlers
  OpenIddict.sln
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  test/OpenIddict.Client.AspNetCore.IntegrationTests/OpenIddict.Client.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Client.IntegrationTests/OpenIddict.Client.IntegrationTests.csproj
  test/OpenIddict.Client.Owin.IntegrationTests/OpenIddict.Client.Owin.IntegrationTests.csproj
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
  test/OpenIddict.Validation.AspNetCore.IntegrationTests/OpenIddict.Validation.AspNetCore.IntegrationTests.csproj
  test/OpenIddict.Validation.AspNetCore.IntegrationTests/OpenIddictValidationAspNetCoreIntegrationTestServer.cs
  test/OpenIddict.Validation.AspNetCore.IntegrationTests/OpenIddictValidationAspNetCoreIntegrationTests.cs
  test/OpenIddict.Validation.IntegrationTests/Certificate.cer
  test/OpenIddict.Validation.IntegrationTests/OpenIddict.Validation.IntegrationTests.csproj
  test/OpenIddict.Validation.IntegrationTests/OpenIddictValidationIntegrationTestClient.cs
  test/OpenIddict.Validation.IntegrationTests/OpenIddictValidationIntegrationTestServer.cs
  test/OpenIddict.Validation.IntegrationTests/OpenIddictValidationIntegrationTests.cs
  test/OpenIddict.Validation.Owin.IntegrationTests/OpenIddict.Validation.Owin.IntegrationTests.csproj
  test/OpenIddict.Validation.Owin.IntegrationTests/OpenIddictValidationOwinIntegrationTestServer.cs
  test/OpenIddict.Validation.Owin.IntegrationTests/OpenIddictValidationOwinIntegrationTests.cs
Labels: enhancement, server stack, validation stack, client stack
