Repository openiddict/openiddict-core, pull requests merged in 2023-11, with the labels that each got.

#1906 Bump the .NET SDK to 8.0.100-rc.2.23502.2
  .github/workflows/build.yml
  global.json
  src/OpenIddict.MongoDb.Models/OpenIddict.MongoDb.Models.csproj
  src/OpenIddict.MongoDb/OpenIddict.MongoDb.csproj
Labels: dependencies

#1907 Bump the .NET SDK to 8.0.200-preview.23530.15
  .github/workflows/build.yml
  global.json
Labels: bug, external, dependencies

#1909 Remove unnecessary usings
  sandbox/OpenIddict.Sandbox.AspNet.Client/App_Start/BundleConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/App_Start/FilterConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/App_Start/RouteConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/Global.asax.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/BundleConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/FilterConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/IdentityConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/AccountController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/HomeController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/ManageController.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandler.cs
  src/OpenIddict.Client/OpenIddictClientBuilder.cs
  src/OpenIddict.Client/OpenIddictClientEvents.Exchange.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTestServer.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Protection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Revocation.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Session.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTestServer.cs
  test/OpenIddict.Validation.AspNetCore.IntegrationTests/OpenIddictValidationAspNetCoreIntegrationTestServer.cs
  test/OpenIddict.Validation.AspNetCore.IntegrationTests/OpenIddictValidationAspNetCoreIntegrationTests.cs
  test/OpenIddict.Validation.Owin.IntegrationTests/OpenIddictValidationOwinIntegrationTestServer.cs
  test/OpenIddict.Validation.Owin.IntegrationTests/OpenIddictValidationOwinIntegrationTests.cs
Labels: enhancement

#1910 Add Zoom to the list of supported providers
  Directory.Build.targets
  gen/OpenIddict.Client.WebIntegration.Generators/OpenIddictClientWebIntegrationGenerator.cs
  shared/OpenIddict.Extensions/OpenIddictHelpers.cs
  src/OpenIddict.Client.DataProtection/OpenIddictClientDataProtectionHandlers.Protection.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Discovery.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreAuthorizationStore.cs
  src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs
  src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.Protection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: enhancement, web providers

#1911 Update the ASP.NET 4.x server sandbox to suppress host authentication
  sandbox/OpenIddict.Sandbox.AspNet.Server/Startup.cs
Labels: bug

#1912 Update the ASP.NET Core/OWIN integrations to allow returning authentication tickets with a null or empty principal
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandler.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandler.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandler.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandler.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandler.cs
Labels: server stack, validation stack, client stack

#1808 Add a .NET 8.0 TFM
  Directory.Build.props
  Directory.Build.targets
  Directory.Packages.props
  NuGet.config
  sandbox/OpenIddict.Sandbox.AspNetCore.Client/OpenIddict.Sandbox.AspNetCore.Client.csproj
  sandbox/OpenIddict.Sandbox.AspNetCore.Server/OpenIddict.Sandbox.AspNetCore.Server.csproj
  sandbox/OpenIddict.Sandbox.Console.Client/OpenIddict.Sandbox.Console.Client.csproj
  sandbox/OpenIddict.Sandbox.WinForms.Client/OpenIddict.Sandbox.WinForms.Client.csproj
  sandbox/OpenIddict.Sandbox.Wpf.Client/OpenIddict.Sandbox.Wpf.Client.csproj
  src/OpenIddict.AspNetCore/OpenIddict.AspNetCore.csproj
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandler.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandler.cs
  src/OpenIddict/OpenIddict.csproj
Labels: enhancement, work in progress

#1913 feat: add constants to match spec
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
Labels: enhancement, community contribution
