Repository openiddict/openiddict-core, pull requests merged in 2024-05, with the labels that each got.

#2062 Allow using unique JSON_ARRAY claims to represent arrays of strings
  shared/OpenIddict.Extensions/OpenIddictHelpers.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.Discovery.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.Introspection.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Discovery.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Introspection.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.cs
Labels: bug, enhancement

#2063 Update Clever provider to not require backchannel ID token
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
Labels: bug, web providers

#2067 Add implicit to the list of grant types supported by the Microsoft and Auth0 providers
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Discovery.cs
Labels: bug, web providers

#2070 Bump Wilson to 7.5.1
  Directory.Packages.props
Labels: dependencies

#2071 Use TimeProvider
  src/OpenIddict.Client/OpenIddictClientBuilder.cs
  src/OpenIddict.Client/OpenIddictClientConfiguration.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.Introspection.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.Protection.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.cs
  src/OpenIddict.Client/OpenIddictClientOptions.cs
  src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs
  src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs
  src/OpenIddict.Core/OpenIddictCoreConfiguration.cs
  src/OpenIddict.Core/OpenIddictCoreExtensions.cs
  src/OpenIddict.Core/OpenIddictCoreOptions.cs
  src/OpenIddict.Quartz/OpenIddictQuartzConfiguration.cs
  src/OpenIddict.Quartz/OpenIddictQuartzExtensions.cs
  src/OpenIddict.Quartz/OpenIddictQuartzJob.cs
  src/OpenIddict.Quartz/OpenIddictQuartzOptions.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Server/OpenIddictServerOptions.cs
  src/OpenIddict.Validation/OpenIddictValidationConfiguration.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Introspection.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Protection.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationOptions.cs
  test/OpenIddict.Quartz.Tests/OpenIddictQuartzConfigurationTests.cs
  test/OpenIddict.Server.Tests/OpenIddictServerBuilderTests.cs
Labels: enhancement, server stack, validation stack, client stack, core stack

#2075 Introduce new advanced APIs in the web provider builders to allow configuring explicit code challenge methods, grant types, response modes and response types
  gen/OpenIddict.Client.WebIntegration.Generators/OpenIddictClientWebIntegrationGenerator.cs
Labels: enhancement, web providers

#2078 Bump the .NET SDK and the .NET packages
  .github/workflows/build.yml
  Directory.Packages.props
  global.json
Labels: dependencies

#2082 Bump Wilson to 7.6.0
  Directory.Packages.props
Labels: dependencies

#2085 Update the ASP.NET 4.8 samples to use file-scoped namespaces
  gen/OpenIddict.Client.WebIntegration.Generators/OpenIddictClientWebIntegrationGenerator.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/App_Start/BundleConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/App_Start/FilterConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/App_Start/RouteConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/Controllers/AuthenticationController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/Controllers/HomeController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/Global.asax.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/Models/ApplicationDbContext.cs
  sandbox/OpenIddict.Sandbox.AspNet.Client/Startup.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/BundleConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/FilterConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/IdentityConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/App_Start/RouteConfig.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/AccountController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/AuthenticationController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/AuthorizationController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/HomeController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/ManageController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Controllers/ResourceController.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Global.asax.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Helpers/AsyncEnumerableExtensions.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Helpers/FormValueRequiredAttribute.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Models/AccountViewModels.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Models/IdentityModels.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Models/ManageViewModels.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Startup.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/ViewModels/Authorization/AuthorizeViewModel.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/ViewModels/Authorization/LogoutViewModel.cs
Labels: enhancement
