Repository openiddict/openiddict-core, pull requests merged in 2024-08, with the labels that each got.

#2163 Pin the workload versions in WorkloadRollback.json
  OpenIddict.sln
  WorkloadRollback.json
  eng/Tools.props
Labels: bug

#2162 Update LinkedIn issuer.
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: bug, external, web providers

#2165 Support the new ASWebAuthenticationSessionCallback API on iOS 17.4+/Mac Catalyst 17.4+/macOS 14.4+
  Directory.Build.props
  WorkloadRollback.json
  sandbox/OpenIddict.Sandbox.Maui.Client/OpenIddict.Sandbox.Maui.Client.csproj
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Authentication.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Session.cs
Labels: enhancement

#2166 Unify platform callbacks handling using a new `OpenIddictClientSystemIntegrationPlatformCallback` type
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationExtensions.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlerFilters.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Authentication.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Session.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHelpers.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationPlatformCallback.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationService.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Discovery.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
Labels: enhancement, system integration

#2167 Remove the compatibility matrix from the README.md file
  README.md
Labels: enhancement

#2170 Use the current address as the default target link URI when `AuthenticationProperties.RedirectUri` is not set
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandlers.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandlers.cs
Labels: enhancement
