Repository openiddict/openiddict-core, pull requests merged in 2024-04, with the labels that each got.

#2051 Update the ASP.NET Core samples to use Kestrel as the default HTTP server
  sandbox/OpenIddict.Sandbox.AspNetCore.Client/Properties/launchSettings.json
  sandbox/OpenIddict.Sandbox.AspNetCore.Server/Properties/launchSettings.json
Labels: enhancement

#2055 Update the OpenIddict client ASP.NET Core/OWIN integrations to support overriding the requested scopes via `AuthenticationProperties`
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreConstants.cs
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandlers.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinConstants.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandlers.cs
Labels: enhancement, client stack

#2056 Update AuthenticationController.cs to include a warning indicating that ASP.NET Core Identity doesn't preserve external claims by default
  sandbox/OpenIddict.Sandbox.AspNetCore.Client/Controllers/AuthenticationController.cs
  sandbox/OpenIddict.Sandbox.AspNetCore.Server/Controllers/AuthenticationController.cs
Labels: enhancement

#2058 Bump Microsoft.Extensions.Http.Resilience to 8.4.0
  Directory.Packages.props
Labels: enhancement, dependencies

#2059 Bump the .NET SDK and dependencies
  .github/workflows/build.yml
  Directory.Packages.props
  global.json
Labels: dependencies

#2060 chore(deps): node16 github actions are depreciated
  .github/workflows/build.yml
  .github/workflows/push.yml
Labels: dependencies
