Repository openiddict/openiddict-core, pull requests merged in 2025-05, with the labels that each got.

#2307 Update the `MapNonStandardResponseParameters` userinfo handler to avoid using `OpenIddictParameter.GetNamedParameters()`
  sandbox/OpenIddict.Sandbox.AspNetCore.Server/Controllers/AuthorizationController.cs
  sandbox/OpenIddict.Sandbox.Maui.Client/MauiProgram.cs
  src/OpenIddict.Abstractions/Descriptors/OpenIddictApplicationDescriptor.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlerFilters.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Authentication.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.Session.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationService.cs
  src/OpenIddict.Client.SystemNetHttp/OpenIddictClientSystemNetHttpHandlers.Exchange.cs
  src/OpenIddict.Client.SystemNetHttp/OpenIddictClientSystemNetHttpHandlers.Introspection.cs
  src/OpenIddict.Client.SystemNetHttp/OpenIddictClientSystemNetHttpHandlers.Revocation.cs
  src/OpenIddict.Client.SystemNetHttp/OpenIddictClientSystemNetHttpHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Userinfo.cs
  src/OpenIddict.Client/OpenIddictClientBuilder.cs
  src/OpenIddict.Client/OpenIddictClientEvents.Revocation.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.Discovery.cs
  src/OpenIddict.Core/OpenIddictCoreOptions.cs
  src/OpenIddict.MongoDb.Models/OpenIddictMongoDbAuthorization.cs
  src/OpenIddict.Server/OpenIddictServerBuilder.cs
  src/OpenIddict.Server/OpenIddictServerEvents.Userinfo.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationBuilder.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictParameterTests.cs
  test/OpenIddict.MongoDb.Tests/OpenIddictMongoDbBuilderTests.cs
  test/OpenIddict.MongoDb.Tests/OpenIddictMongoDbExtensionsTests.cs
  test/OpenIddict.Validation.IntegrationTests/OpenIddictValidationIntegrationTestClient.cs
Labels: enhancement, web providers

#2306 Adds Contentful web provider
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: web providers, community contribution

#2310 Special-case `JsonValue` instances that wrap a `JsonElement` object
  shared/OpenIddict.Extensions/OpenIddictHelpers.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
Labels: enhancement

#2311 Update `OpenIddictParameter` to return empty immutable arrays instead of uninitialized instances
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictParameterTests.cs
Labels: enhancement

#2313 Update the Alibaba/Battle.net/Cognito/Lark/Zoho providers to throw an exception when an invalid/unsupported region is specified
  gen/OpenIddict.Client.WebIntegration.Generators/OpenIddictClientWebIntegrationGenerator.cs
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: enhancement, web providers

#2314 Update the Zoho provider to support the new United Kingdom region
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: enhancement

#2315 Update the provider generator to support generating string constants
  gen/OpenIddict.Client.WebIntegration.Generators/OpenIddictClientWebIntegrationGenerator.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xsd
Labels: enhancement

#2316 Update the Discord provider to use /users/@me instead of /oauth2/@me
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: web providers

#2319 Bump Wilson to 8.10.0
  Directory.Packages.props
Labels: dependencies

#2320 Change the maximum length of the `OpenIddictEntityFrameworkToken`/`OpenIddictEntityFrameworkCoreToken.Type` column from 50 to 150
  src/OpenIddict.EntityFramework/Configurations/OpenIddictEntityFrameworkTokenConfiguration.cs
  src/OpenIddict.EntityFrameworkCore/Configurations/OpenIddictEntityFrameworkCoreTokenConfiguration.cs
Labels: bug

#2323 Remove the runtime checks that prevent the generic version of OpenIddict.Client.SystemIntegration from being used on Android/iOS/macOS/Mac Catalyst
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationConfiguration.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationExtensions.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHelpers.cs
Labels: enhancement, system integration

#2324 Fix the Android/iOS/Mac Catalyst/macOS workloads detection logic
  Directory.Build.props
Labels: bug, infrastructure

#2325 Fix invalid resource identifiers
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: bug

#2329 Move the token binding methods constants to a private nested class exposing URI-style values
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
  src/OpenIddict.Client.SystemNetHttp/OpenIddictClientSystemNetHttpHandlers.cs
Labels: enhancement

#2332 Improve the WWW-Authenticate parsing logic
  src/OpenIddict.Client.SystemNetHttp/OpenIddictClientSystemNetHttpHandlers.cs
  src/OpenIddict.Validation.SystemNetHttp/OpenIddictValidationSystemNetHttpHandlers.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTestClient.cs
  test/OpenIddict.Validation.IntegrationTests/OpenIddictValidationIntegrationTestClient.cs
Labels: enhancement, validation stack, client stack

#2333 Implement new audience and presenter validation logic as part of the `ValidateToken` event
  shared/OpenIddict.Extensions/OpenIddictHelpers.cs
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Client/OpenIddictClientEvents.Protection.cs
  src/OpenIddict.Client/OpenIddictClientExtensions.cs
  src/OpenIddict.Client/OpenIddictClientHandlerFilters.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.Protection.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.cs
  src/OpenIddict.Server/OpenIddictServerConfiguration.cs
  src/OpenIddict.Server/OpenIddictServerEvents.Protection.cs
  src/OpenIddict.Server/OpenIddictServerExtensions.cs
  src/OpenIddict.Server/OpenIddictServerHandlerFilters.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Device.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Session.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.Userinfo.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation/OpenIddictValidationEvents.Protection.cs
  src/OpenIddict.Validation/OpenIddictValidationExtensions.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlerFilters.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.Protection.cs
  src/OpenIddict.Validation/OpenIddictValidationHandlers.cs
  test/OpenIddict.Server.IntegrationTests/OpenIddictServerIntegrationTests.Userinfo.cs
  test/OpenIddict.Validation.IntegrationTests/OpenIddictValidationIntegrationTests.cs
Labels: enhancement, important, server stack, validation stack, client stack
