Repository openiddict/openiddict-core, pull requests merged in 2025-03, with the labels that each got.

#2265 Migrate to the new SLNX format
  OpenIddict.sln
  OpenIddict.slnx
Labels: enhancement

#2272 Remove the members obsoleted in OpenIddict 6.1
  Directory.Packages.props
  src/OpenIddict.Abstractions/OpenIddictConstants.cs
  src/OpenIddict.Abstractions/OpenIddictResources.resx
  src/OpenIddict.Abstractions/Primitives/OpenIddictRequest.cs
  src/OpenIddict.Server.AspNetCore/OpenIddict.Server.AspNetCore.csproj
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreBuilder.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreConstants.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreExtensions.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlerFilters.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Session.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreOptions.cs
  src/OpenIddict.Server.Owin/OpenIddict.Server.Owin.csproj
  src/OpenIddict.Server.Owin/OpenIddictServerOwinBuilder.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinConstants.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinExtensions.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlerFilters.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Authentication.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinOptions.cs
Labels: enhancement, server stack, abstractions

#2274 Fix the ID2183 error message to point to the correct endpoint name
  src/OpenIddict.Abstractions/OpenIddictResources.resx
Labels: bug

#2275 Use the `CreateAsyncScope()` helper to avoid having to manually cast `IServiceProvider` to `IAsyncDisposable`
  sandbox/OpenIddict.Sandbox.AspNetCore.Client/Worker.cs
  sandbox/OpenIddict.Sandbox.AspNetCore.Server/Worker.cs
  sandbox/OpenIddict.Sandbox.Console.Client/Worker.cs
  sandbox/OpenIddict.Sandbox.WinForms.Client/Worker.cs
  sandbox/OpenIddict.Sandbox.Wpf.Client/Worker.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationService.cs
  src/OpenIddict.Client/OpenIddictClientService.cs
  src/OpenIddict.Quartz/OpenIddictQuartzJob.cs
  src/OpenIddict.Validation/OpenIddictValidationService.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
  test/OpenIddict.Validation.Owin.IntegrationTests/OpenIddictValidationOwinIntegrationTests.cs
Labels: enhancement

#2277 Set NuGetAuditMode to "all" to enable vulnerable transitive dependencies warnings
  Directory.Build.props
  Directory.Packages.props
  sandbox/OpenIddict.Sandbox.AspNetCore.Server/OpenIddict.Sandbox.AspNetCore.Server.csproj
  src/OpenIddict.EntityFrameworkCore/OpenIddict.EntityFrameworkCore.csproj
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictConverterTests.cs
  test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictMessageTests.cs
Labels: enhancement, dependencies

#2280 Bring back store registration methods supporting open generics
  src/OpenIddict.Core/OpenIddictCoreBuilder.cs
Labels: enhancement, core stack

#2281 Update the ASP.NET 4.8 samples to register the ApplicationDbContext type
  sandbox/OpenIddict.Sandbox.AspNet.Client/Startup.cs
  sandbox/OpenIddict.Sandbox.AspNet.Server/Startup.cs
Labels: bug

#2282 Use `Uri.TryCreate()` to build the base and request URIs used by OpenIddict
  src/OpenIddict.Client.AspNetCore/OpenIddictClientAspNetCoreHandlers.cs
  src/OpenIddict.Client.Owin/OpenIddictClientOwinHandlers.cs
  src/OpenIddict.Client.SystemIntegration/OpenIddictClientSystemIntegrationHandlers.cs
  src/OpenIddict.Client/OpenIddictClientHandlers.cs
  src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs
  src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.cs
  src/OpenIddict.Server/OpenIddictServerHandlers.cs
  src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs
  src/OpenIddict.Validation.Owin/OpenIddictValidationOwinHandlers.cs
  test/OpenIddict.Server.AspNetCore.IntegrationTests/OpenIddictServerAspNetCoreIntegrationTests.cs
  test/OpenIddict.Server.Owin.IntegrationTests/OpenIddictServerOwinIntegrationTests.cs
Labels: bug

#2283 Bump MSBuild.SDK.SystemWeb to 4.0.97
  Directory.Build.props
  global.json
  sandbox/OpenIddict.Sandbox.AspNet.Client/OpenIddict.Sandbox.AspNet.Client.csproj
  sandbox/OpenIddict.Sandbox.AspNet.Server/OpenIddict.Sandbox.AspNet.Server.csproj
Labels: dependencies

#2285 Update the web providers XSD to allow using all the supported client authentication methods
  src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Revocation.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xsd
Labels: enhancement, web providers

#2284 Adds Linear, Miro, and Webflow web providers
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Revocation.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Userinfo.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs
  src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml
Labels: web providers, community contribution
